### ISSUE TITLE
LoadingPhase for Uncooked module

### ISSUE THREAD

**Issue by inequity** [MagForceSeven/UE-K2-Nodes#2]
Hi again,

I'm having a problem where the node I've created disappears when reloading the engine. From googling, seems like it may be related to the LoadingPhase for the Uncooked module. I've seen people setting it to PreDefault. If I do this, I crash on launch.

Have you seen a similar problem? What LoadingPhase do you have set for your Uncooked module?

Thanks!

**Comment by MagForceSeven** [comment]
I do recall having run into that problem at one time or another but I don't recall what was done to resolve it. All the Uncooked modules that I have in my home project and that we have at work are all set to Default.
